### PR TITLE
Merge upstream v1.12.4

### PR DESCRIPTION
**Pull request by tomtseng**
(This PR should not be squashed.)

Note: New config param `enablePassingHacks` should be set to `false` if we want to keep behavior close to v1.10.0 (e.g., for cyclic adversary).

## Testing

Two tests to sanity check that the merge PRs won’t cause major issues for us:

1. Run a training run with victim visits = 1, check that we still find the passing attack. Turn gatekeeping on too to check that gatekeeper still works.
2. Run GTP games, with one player being pass-adv/cyclic-adv running on the merge PR and the other player being a victim running on `stable`. Check the win rate is similar to the same setup but with adv running on `stable` too

Results here:  [experiment page](https://www.notion.so/chaiberkeley/Nov-2022-merge-PR-v1-12-4-merge-PR-testing-af0cc4819eb043fe8451633c25fcc770)

### CODE REVIEW

**Review by ed1d1a8d — COMMENTED** [review]
Code changes LGTM, they show now merge conflicts either from diff3 or p4merge (p4merge is better at merging).

However, like previous PRs, there are some conflicts on test logs. Listing the conflicting files. Are changes are expected here?
```
cpp/tests/results/analysis/pvvisits.txt.log
cpp/tests/results/analysis/pvvisits.txt.stderr
cpp/tests/results/analysis/pvvisits.txt.stdout
cpp/tests/results/analysis/pvvisits_nograph.stderr
cpp/tests/results/analysis/pvvisits_nograph.stdout
cpp/tests/results/analysis/pvvisits_nograph.txt.log
cpp/tests/results/gtp/ending.txt.log
cpp/tests/results/gtp/ending.txt.stderr
cpp/tests/results/runSearchTests-iNHWC-cNHWC.txt
cpp/tests/results/runSearchTests-r4-iNHWC-cNHWC.txt
cpp/tests/results/runSearchTestsFP16-iNHWC-cNHWC.txt
cpp/tests/results/runSearchTestsFP16-r4-iNHWC-cNHWC.txt
cpp/tests/results/runSearchTestsV3-g2-iNHWC-cNHWC.txt
cpp/tests/results/runSearchTestsV3FP16-g2-iNHWC-cNHWC.txt
cpp/tests/results/runSearchTestsV8FP16.txt
```

**Comment by tomtseng** [comment]
Updated test results and looked at diff with upstream v1.12.4 — I think the diff looks OK.

**Review by ed1d1a8d — CHANGES_REQUESTED** [review]
Defaulting to you on the test logs looking good. One final request: could we run a few games using a standard KataGo network (e.g. cp505) with this code and upstream KataGo v1.12.4 code? We should ideally get a 50-50 winrate if the hyperparams are matched. If we get this, combined with the other test results, I'd be pretty confident our code is correct.

We should run the networks using the KataGo v1.12.4 default settings to test out all the new features in the codebase.

Feel free to just do this directly on the v1.13 code too, if this test passes there, no need to do it here as well.

**Comment by tomtseng** [comment]
Ran ~400 cp505 games and ~400 b18 games, results are around 50-50: https://www.notion.so/chaiberkeley/v1-13-0-merge-PR-testing-44ee9b50a90f4fc7bdc796ec6f5690e4?pvs=4#0e4e224793024985ab6d2d9b43bd7f03

**Review by ed1d1a8d — APPROVED** [review]
Thanks for the running the additional tests. LGTM now. Will continue reviewing the other PRs now.

**Pull request merged**
